import type { Metadata } from "next";
import React from "react";
import {Container} from "@mui/material";
import "./global.css";
import Header from "../components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
        <Container sx={{ bgcolor: "#ccc", height: "100vh" }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
